
import { Broker, InternationalBroker, CryptoExchange, FeeType } from './types';
import { 
  TrendingUp, ShieldCheck, Zap, Smartphone, Globe, Award, Bitcoin, 
  Landmark, Rocket, Briefcase, Crown, Building2, LineChart, Cpu, 
  Gem, Wallet, Anchor, Coins
} from 'lucide-react';

// Canlıya alırken bu tarihi manuel güncelleyerek kullanıcıya güven verebilirsiniz.
// Gerçek bir backend kurulursa bu tarih API'den gelecektir.
export const LAST_UPDATED = new Date().toLocaleDateString('tr-TR', { month: 'long', year: 'numeric' });

export const BROKERS: Broker[] = [
  {
    id: '1',
    name: 'Midas',
    logoColor: 'bg-yellow-400',
    icon: Zap,
    logoUrl: 'https://logo.clearbit.com/getmidas.com',
    commissionRate: { share: 0, viop: 0 }, 
    minCommission: 0, 
    accountFee: 'Ücretsiz',
    liveData: FeeType.FREE,
    mobileAppScore: 4.8,
    features: ['ABD & BIST Tek Hesap', 'Ücretsiz Canlı Veri', 'Hesap/Saklama Ücreti Yok', 'Parça Hisse Alımı', 'Döviz Makası Düşük'],
    description: 'Borsa İstanbul işlemlerinde hacim şartı olmaksızın sabit düşük komisyon sunar. VİOP işlemleri henüz aktif değildir.',
    volumeRequirement: 'Yok',
    accountOpenUrl: 'https://www.getmidas.com/',
    tags: ['Komisyonsuz', 'Popüler', 'Modern']
  },
  {
    id: '13',
    name: 'Trive',
    logoColor: 'bg-slate-950',
    icon: Rocket,
    logoUrl: 'https://logo.clearbit.com/trive.com.tr',
    commissionRate: { share: 4, viop: 4 },
    minCommission: 0,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 4.3,
    features: ['Kredili İşlemde 0 Komisyon', 'Hızlı Emir İletimi', 'Modern Arayüz', 'Sigorta Güvencesi', 'Global Erişim'],
    description: 'Komisyonsuz kredi kampanyaları ve düşük işlem komisyonları ile öne çıkar. Hacim şartı aramadan rekabetçi oranlar sunar.',
    volumeRequirement: 'Kampanyaya göre',
    accountOpenUrl: 'https://www.trive.com.tr/hesap-ac',
    tags: ['Kredili İşlem', 'Rekabetçi']
  },
  {
    id: '12',
    name: 'Tacirler Yatırım',
    logoColor: 'bg-blue-900',
    icon: Briefcase,
    logoUrl: 'https://logo.clearbit.com/tacirler.com.tr',
    commissionRate: { share: 7, viop: 5 },
    minCommission: 1,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 3.8,
    features: ['Çok Düşük Maliyet', 'FX ve Türev Piyasalar', 'Yüksek Kaldıraç İmkanı', 'Geniş Araştırma Arşivi', 'Bağımsız Kurum Esnekliği'],
    description: 'Aktif traderlar için piyasadaki en düşük komisyon oranlarından birini sunar. VİOP ve FX tarafında güçlüdür.',
    volumeRequirement: 'Yok',
    accountOpenUrl: 'https://www.tacirler.com.tr/hesap-ac',
    tags: ['Trader Dostu', 'Düşük Maliyet']
  },
  {
    id: '21',
    name: 'Burgan Yatırım',
    logoColor: 'bg-yellow-500',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/burganyatirim.com.tr',
    commissionRate: { share: 10, viop: 8 },
    minCommission: 1,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 4.2,
    features: ['Dijital Hesap Açılışı', 'Trademaster Altyapısı', 'Rekabetçi Kur', 'Özel Müşteri Temsilcisi', 'Hızlı Platform'],
    description: 'ON Dijital Bankacılık müşterilerine özel avantajlı oranlar sunabilir. Standart dijital hesap açılışlarında oranlar makuldür.',
    accountOpenUrl: 'https://www.burganyatirim.com.tr/',
    tags: ['Dijital', 'Hızlı']
  },
  {
    id: '16',
    name: 'A1 Capital',
    logoColor: 'bg-red-600',
    icon: TrendingUp,
    logoUrl: 'https://logo.clearbit.com/a1capital.com.tr',
    commissionRate: { share: 7, viop: 5 },
    minCommission: 2,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 3.7,
    features: ['Hızlı Platform Altyapısı', 'Halka Arz Odaklı', 'Anlık Piyasa Analizleri', 'Yüksek İşlem Hacmi', 'Bireysel Portföy Yönetimi'],
    description: 'Halka arzlardaki etkinliğiyle bilinir. Yüksek hacimli işlemlerde oranlar daha da aşağı çekilebilir.',
    accountOpenUrl: 'https://a1capital.com.tr/hesap-ac/',
    tags: ['Halka Arz', 'Hızlı İşlem']
  },
  {
    id: '5',
    name: 'Info Yatırım',
    logoColor: 'bg-red-600',
    icon: LineChart,
    logoUrl: 'https://logo.clearbit.com/infoyatirim.com',
    commissionRate: { share: 7, viop: 5 },
    minCommission: 2,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 4.0,
    features: ['Hızlı Hesap Açılışı', 'VİOP Uzmanlığı', 'Günlük Bültenler', 'Algo-Trading API', 'YouTube Analizleri'],
    description: 'VİOP tarafında uzmanlaşmış kurumlardan biridir. Algo trading ve API desteği güçlüdür.',
    accountOpenUrl: 'https://infoyatirim.com/hesap-ac/',
    tags: ['VİOP', 'Analiz']
  },
  {
    id: '22',
    name: 'Alnus Yatırım',
    logoColor: 'bg-red-700',
    icon: Cpu,
    logoUrl: 'https://logo.clearbit.com/alnusyatirim.com',
    commissionRate: { share: 10, viop: 7 },
    minCommission: 2,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 3.9,
    features: ['Gelişmiş Mobil Uygulama', 'Halka Arz Katılımı', 'FX Piyasaları', 'Dinamik Komisyon', 'Yatırım Danışmanlığı'],
    description: 'Teknoloji odaklı yatırımları ile bilinir. VİOP ve FX piyasalarında geniş ürün yelpazesi sunar.',
    accountOpenUrl: 'https://www.alnusyatirim.com/hesap-ac',
    tags: ['Teknolojik', 'Halka Arz']
  },
  {
    id: '3',
    name: 'Osmanlı Yatırım',
    logoColor: 'bg-red-700',
    icon: Crown,
    logoUrl: 'https://logo.clearbit.com/osmanlimenkul.com.tr',
    commissionRate: { share: 3.75, viop: 2 },
    minCommission: 0,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.5,
    features: ['Gelişmiş e-Şube', 'Otomatik Emirler', 'Hacme Göre Veri Ekranı', 'Robo Danışman', 'VİOP Nemalandırma'],
    description: 'İşlem hacmine göre otomatik düşen komisyon yapısı vardır. Başlangıç oranları rekabetçidir.',
    volumeRequirement: 'Hacme göre',
    accountOpenUrl: 'https://www.osmanlimenkul.com.tr/hesap-ac',
    tags: ['Teknolojik', 'Robo Danışman']
  },
  {
    id: '23',
    name: 'İntegral Yatırım',
    logoColor: 'bg-red-600',
    icon: LineChart,
    logoUrl: 'https://logo.clearbit.com/integralyatirim.com.tr',
    commissionRate: { share: 10, viop: 8 },
    minCommission: 5,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.1,
    features: ['Güçlü Analiz Kadrosu', 'Forex Kökenli', 'Eğitim Desteği', 'Birebir İletişim', 'Hızlı Para Transferi'],
    description: 'Analiz departmanı sektörde oldukça saygındır. Forex kökenli olduğu için türev piyasalara (VİOP) hakimdir.',
    accountOpenUrl: 'https://integralyatirim.com.tr/gercek-hesap',
    tags: ['Analiz Lideri', 'Forex']
  },
  {
    id: '9',
    name: 'Gedik Yatırım',
    logoColor: 'bg-red-600',
    icon: Building2,
    logoUrl: 'https://logo.clearbit.com/gedikyatirim.com.tr',
    commissionRate: { share: 15, viop: 10 },
    minCommission: 3,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.1,
    features: ['Gedik Trader', 'Geniş Şube Ağı', 'Yatırım Kulübü', 'Ücretsiz Analiz', 'Private Banking'],
    description: 'Sektörün köklü kurumlarından. VİOP işlemlerinde Gedik Trader platformu üzerinden hızlı işlem imkanı sağlar.',
    accountOpenUrl: 'https://www.gedik.com/hesap-ac',
    tags: ['Köklü', 'Yaygın Ağ']
  },
  {
    id: '14',
    name: 'Phillip Capital',
    logoColor: 'bg-blue-700',
    icon: Globe,
    logoUrl: 'https://logo.clearbit.com/phillipcapital.com.tr',
    commissionRate: { share: 10, viop: 8 },
    minCommission: 1,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 3.9,
    features: ['Global Erişim', 'Profesyonel Platformlar', 'Uluslararası Fonlar', 'Vadeli İşlemler', 'Singapur Güvencesi'],
    description: 'Türev araçlarda (VİOP) global deneyimi ile öne çıkar. Yabancı yatırımcıların da tercih ettiği bir kurumdur.',
    accountOpenUrl: 'https://www.phillipcapital.com.tr/hesap-ac',
    tags: ['Uluslararası', 'Türev']
  },
  {
    id: '24',
    name: 'Marbaş Menkul',
    logoColor: 'bg-red-500',
    icon: Briefcase,
    logoUrl: 'https://logo.clearbit.com/marbasmenkul.com.tr',
    commissionRate: { share: 10, viop: 8 },
    minCommission: 2,
    accountFee: 'Sadece MKK',
    liveData: FeeType.FREE,
    mobileAppScore: 3.6,
    features: ['Hacme Özel Oranlar', 'Müşteri Odaklı', 'Köklü Geçmiş', 'VİOP Teminat', 'Ücretsiz Eğitim'],
    description: 'Info Yatırım iştirakidir. VİOP işlemlerinde esnek teminat ve komisyon yapıları sunabilir.',
    accountOpenUrl: 'https://marbasmenkul.com.tr/hesap-ac',
    tags: ['Butik', 'Esnek']
  },
  {
    id: '19',
    name: 'Yatırım Finansman',
    logoColor: 'bg-orange-600',
    icon: Building2,
    logoUrl: 'https://logo.clearbit.com/yf.com.tr',
    commissionRate: { share: 18, viop: 12 },
    minCommission: 5,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.3,
    features: ['İlk Aracı Kurum', 'Derinlikli Raporlar', 'Güçlü Sermaye', 'Kurumsal Hizmet', 'Geniş Portföy'],
    description: 'Türkiye\'nin ilk aracı kurumudur. Kurumsal ve nitelikli bireysel yatırımcılara hitap eder.',
    accountOpenUrl: 'https://www.yf.com.tr/hesap-ac',
    tags: ['İlk Kurum', 'Prestijli']
  },
  {
    id: '10',
    name: 'QNB Finansinvest',
    logoColor: 'bg-rose-900',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/qnbfi.com',
    commissionRate: { share: 15, viop: 10 },
    minCommission: 5,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.2,
    features: ['Kişiye Özel Danışman', 'QNB Mobil Entegre', 'Zengin Fon Çeşitliliği', 'Varlık Yönetimi', 'Piyasa Yorumları'],
    description: 'QNB Finansbank iştirakidir. Dijital kanallardan yapılan işlemlerde standart oranlar uygulanır.',
    accountOpenUrl: 'https://www.qnbfi.com/hesap-ac',
    tags: ['Banka İştiraki', 'Varlık Yönetimi']
  },
  {
    id: '15',
    name: 'Deniz Yatırım',
    logoColor: 'bg-blue-800',
    icon: Anchor,
    logoUrl: 'https://logo.clearbit.com/denizyatirim.com',
    commissionRate: { share: 15, viop: 12 },
    minCommission: 5,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.4,
    features: ['Algolab ile Algoritmik İşlem', 'DenizTrader', 'Yapay Zeka Önerileri', 'Kredili İşlem', 'Hızlı Hesap'],
    description: 'Algolab uygulaması ile VİOP ve hisse tarafında algoritmik emirler oluşturulabilir. Standart oranlar banka ortalamasındadır.',
    accountOpenUrl: 'https://www.denizyatirim.com/hesap-ac',
    tags: ['Algoritmik', 'Yapay Zeka']
  },
  {
    id: '18',
    name: 'Oyak Yatırım',
    logoColor: 'bg-red-700',
    icon: ShieldCheck,
    logoUrl: 'https://logo.clearbit.com/oyakyatirim.com.tr',
    commissionRate: { share: 18, viop: 14 },
    minCommission: 5,
    accountFee: 'Sadece MKK',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.0,
    features: ['OYAK Güvencesi', 'Pratik İşlem', 'Kurumsal Finansman', 'Geniş Fon Ailesi', 'Emtia İşlemleri'],
    description: 'OYAK Grubu iştirakidir. Güvenilirlik ön plandadır, VİOP işlemleri için sağlam bir altyapı sunar.',
    accountOpenUrl: 'https://www.oyakyatirim.com.tr/hesap-ac',
    tags: ['OYAK Grubu', 'Güvenli']
  },
  {
    id: '7',
    name: 'Ak Yatırım',
    logoColor: 'bg-red-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/akbank.com',
    commissionRate: { share: 20, viop: 16 },
    minCommission: 5,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 3.8,
    features: ['TradeAll Platformu', 'Tek Ekran Global/Yerel', 'Türev Araçlar', 'Algo İşlemler', 'Sektör Raporları'],
    description: 'TradeAll platformu ile VİOP, Forex ve Hisse işlemlerini tek ekrandan yönetme imkanı verir.',
    accountOpenUrl: 'https://www.akyatirim.com.tr/hesap-ac',
    tags: ['Profesyonel', 'TradeAll']
  },
  {
    id: '20',
    name: 'TEB Yatırım',
    logoColor: 'bg-emerald-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/tebyatirim.com.tr',
    commissionRate: { share: 20, viop: 16 },
    minCommission: 8,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.1,
    features: ['BNP Paribas Ortağı', 'Pratik Borsa', 'Global Raporlar', 'Araştırma Desteği', 'Kurumsal Hizmet'],
    description: 'BNP Paribas ortaklığı ile güçlü bir türev (VİOP) işlem masasına sahiptir.',
    accountOpenUrl: 'https://www.tebyatirim.com.tr/hesap-ac',
    tags: ['Global Ortak', 'Kurumsal']
  },
  {
    id: '4',
    name: 'Garanti BBVA Yatırım',
    logoColor: 'bg-green-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/garantibbvayatirim.com.tr',
    commissionRate: { share: 19, viop: 15 },
    minCommission: 10,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.FIXED,
    mobileAppScore: 4.6,
    features: ['e-Trader Mobil', 'Banka Entegrasyonu', 'Görüntülü Görüşme', 'Model Portföy', 'Yabancı Hisse'],
    description: 'Garanti BBVA Mobil üzerinden işlem kolaylığı sunar. Standart komisyon oranları uygulanır.',
    accountOpenUrl: 'https://www.garantibbvayatirim.com.tr/hesap-ac',
    tags: ['Güvenilir', 'Entegre']
  },
  {
    id: '6',
    name: 'Yapı Kredi Yatırım',
    logoColor: 'bg-blue-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/ykyatirim.com.tr',
    commissionRate: { share: 19, viop: 15 },
    minCommission: 8,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.4,
    features: ['Yatırım Dünyam', 'TradeBox', 'Model Portföy', 'Halka Arz Lideri', 'Sürdürülebilir Fonlar'],
    description: 'Yatırım Dünyam uygulaması ile hisse ve VİOP işlemleri entegre şekilde yapılabilir.',
    accountOpenUrl: 'https://www.ykyatirim.com.tr/hesap-ac',
    tags: ['Kullanıcı Dostu', 'Banka']
  },
  {
    id: '2',
    name: 'İş Yatırım',
    logoColor: 'bg-blue-700',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/isyatirim.com.tr',
    commissionRate: { share: 20, viop: 16 },
    minCommission: 5,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.TIERED,
    mobileAppScore: 4.5,
    features: ['TradeMaster', 'Kapsamlı Araştırma', 'Uluslararası Piyasa', 'Hızlı Emir', 'Güçlü Sermaye'],
    description: 'TradeMaster platformu VİOP oyuncuları için gelişmiş özellikler sunar. Komisyon oranları hacme göre değişebilir.',
    volumeRequirement: '10.000 TL alt limit',
    accountOpenUrl: 'https://www.isyatirim.com.tr/tr-tr/hesap-ac/Sayfalar/default.aspx',
    tags: ['Piyasa Lideri', 'TradeMaster']
  },
  {
    id: '17',
    name: 'Halk Yatırım',
    logoColor: 'bg-sky-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/halkyatirim.com.tr',
    commissionRate: { share: 15, viop: 12 },
    minCommission: 8,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.FIXED,
    mobileAppScore: 3.7,
    features: ['HalkTrader', 'Kamu Bankası', 'Halka Arz Kolaylığı', 'Yaygın Şube', 'Temettü Yatırımı'],
    description: 'Kamu bankası iştiraki olarak güvenli VİOP işlemleri sunar. Oranlar özel bankalara göre daha düşüktür.',
    accountOpenUrl: 'https://www.halkyatirim.com.tr/hesap-ac',
    tags: ['Kamu', 'Güvenli']
  },
  {
    id: '8',
    name: 'Ziraat Yatırım',
    logoColor: 'bg-red-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/ziraatyatirim.com.tr',
    commissionRate: { share: 15, viop: 12 },
    minCommission: 10,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.FIXED,
    mobileAppScore: 3.6,
    features: ['ZBorsa Mobil', 'Kamu Bankası Güvencesi', 'Halka Arz Erişimi', 'Yaygın Ağ', 'Uzun Vadeli Odak'],
    description: 'ZBorsa üzerinden hisse ve VİOP işlemleri yapılabilir. Kamu bankası avantajı ile standart oranlar daha uygundur.',
    accountOpenUrl: 'https://www.ziraatyatirim.com.tr/hesap-ac',
    tags: ['Kamu', 'Halka Arz']
  },
  {
    id: '11',
    name: 'Vakıf Yatırım',
    logoColor: 'bg-amber-400',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/vakifyatirim.com.tr',
    commissionRate: { share: 15, viop: 12 },
    minCommission: 8,
    accountFee: 'Dönemsel Kesinti',
    liveData: FeeType.FIXED,
    mobileAppScore: 3.8,
    features: ['TradeOnline', 'Halka Arz Liderliği', 'Kamu Güvencesi', 'VIOP Teminat', 'Portföy Yönetimi'],
    description: 'Vakıfbank iştirakidir. VİOP teminat tamamlama ve işlem süreçleri entegredir.',
    accountOpenUrl: 'https://www.vakifyatirim.com.tr/hesap-ac',
    tags: ['Kamu', 'Güvenli']
  }
];

export const INTERNATIONAL_BROKERS: InternationalBroker[] = [
  {
    id: 'int_1',
    name: 'Midas',
    logoColor: 'bg-yellow-400',
    icon: Zap,
    logoUrl: 'https://logo.clearbit.com/getmidas.com',
    commissionRate: '1.5 USD',
    minCommission: '1.5 USD',
    custodyFee: 'Ücretsiz',
    mobileAppScore: 4.8,
    features: ['Canlı Veri Ücretsiz', '500.000 USD SIPC Sigortası', 'Hızlı Dolar Al/Sat', 'ABD Borsaları Tek Hesap'],
    description: 'ABD borsaları için sabit 1.5 USD işlem ücreti alır. Gizli masraf, saklama ücreti veya minimum bakiye şartı yoktur.',
    accountOpenUrl: 'https://www.getmidas.com/',
    tags: ['Sabit Ücret', 'Sigortalı']
  },
  {
    id: 'int_6',
    name: 'Trive',
    logoColor: 'bg-slate-950',
    icon: Rocket,
    logoUrl: 'https://logo.clearbit.com/trive.com.tr',
    commissionRate: '1 USD (Min)',
    minCommission: '1 USD',
    custodyFee: 'Ücretsiz',
    mobileAppScore: 4.3,
    features: ['Düşük Komisyon', 'Avrupa Borsaları', 'Kullanıcı Dostu', 'Hızlı Hesap'],
    description: 'ABD hisse senedi işlemlerinde 1 USD minimum komisyon uygular. Avrupa borsalarına da rekabetçi oranlarla erişim sağlar.',
    accountOpenUrl: 'https://www.trive.com.tr/hesap-ac',
    tags: ['Avrupa Borsaları', 'Ekonomik']
  },
  {
    id: 'int_2',
    name: 'Phillip Capital',
    logoColor: 'bg-blue-700',
    icon: Globe,
    logoUrl: 'https://logo.clearbit.com/phillipcapital.com.tr',
    commissionRate: '8 USD (Min)',
    minCommission: 'Değişken',
    custodyFee: 'Aylık 10 USD (Bakiye altı)',
    mobileAppScore: 3.9,
    features: ['Asya & ABD Erişimi', 'Profesyonel Platform', 'Geniş Ürün Gamı', 'Singapur Merkezli'],
    description: 'Sadece ABD değil, Singapur, Japonya, Hong Kong gibi Asya borsalarına da erişim sağlar. Min. komisyon borsaya göre 8-15 USD arası değişir.',
    accountOpenUrl: 'https://www.phillipcapital.com.tr/hesap-ac',
    tags: ['Asya Borsaları', 'Geniş Erişim']
  },
  {
    id: 'int_5',
    name: 'Gedik Yatırım',
    logoColor: 'bg-red-600',
    icon: Building2,
    logoUrl: 'https://logo.clearbit.com/gedikyatirim.com.tr',
    commissionRate: '%0.20 (Min 10 USD)',
    minCommission: '10-25 USD',
    custodyFee: 'Değişken',
    mobileAppScore: 4.1,
    features: ['Saxo Bank Altyapısı', 'Geniş Piyasa', 'Eğitim Desteği', 'Profesyonel Analiz'],
    description: 'Yurtdışı işlemlerinde işlem hacmine göre değişen oranlar sunar. Standart olarak min. komisyon borsaya göre 10 ile 25 birim para arasında değişir.',
    accountOpenUrl: 'https://www.gedik.com/hesap-ac',
    tags: ['Saxo Altyapı', 'Profesyonel']
  },
  {
    id: 'int_4',
    name: 'Ak Yatırım (TradeAll)',
    logoColor: 'bg-red-600',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/akbank.com',
    commissionRate: '%0.20 / Min 15 USD',
    minCommission: '15 USD',
    custodyFee: 'Yıllık %0.2',
    mobileAppScore: 3.8,
    features: ['TradeAll TR', 'FX ve CFD', 'Hızlı Emir', 'Kaldıraçlı İşlemler'],
    description: 'TradeAll platformu üzerinden ABD borsalarında minimum 15 USD işlem ücreti uygulanır. Profesyonel traderlar için CFD seçenekleri geniştir.',
    accountOpenUrl: 'https://www.akyatirim.com.tr/hesap-ac',
    tags: ['CFD', 'Kaldıraç']
  },
  {
    id: 'int_3',
    name: 'İş Yatırım (TradeMaster)',
    logoColor: 'bg-blue-700',
    icon: Landmark,
    logoUrl: 'https://logo.clearbit.com/isyatirim.com.tr',
    commissionRate: '%0.25 / Min 25 USD',
    minCommission: '25 USD',
    custodyFee: 'Aylık %0.01',
    mobileAppScore: 4.5,
    features: ['Güçlü Araştırma', 'Eurobond', 'Geniş Borsa Ağı', 'TradeMaster Intl'],
    description: 'TradeMaster International ile işlem yapılır. Standart komisyon binde 2.5, minimum işlem ücreti ise 25 USD/EUR seviyesindedir.',
    accountOpenUrl: 'https://www.isyatirim.com.tr/tr-tr/hesap-ac/Sayfalar/default.aspx',
    tags: ['Eurobond', 'Kurumsal']
  },
  {
    id: 'int_7',
    name: 'Yatırım Finansman',
    logoColor: 'bg-orange-600',
    icon: Building2,
    logoUrl: 'https://logo.clearbit.com/yf.com.tr',
    commissionRate: '%0.20 / Min 20 USD',
    minCommission: '20 USD',
    custodyFee: 'Değişken',
    mobileAppScore: 4.3,
    features: ['Geniş Ülke Erişimi', 'Derinlikli Raporlar', 'Kurumsal Güvence', 'ETF İşlemleri'],
    description: 'Global piyasalarda geniş bir erişim ağı sunar. İşlem hacmine göre komisyon oranlarında esneklik sağlanabilir.',
    accountOpenUrl: 'https://www.yf.com.tr/hesap-ac',
    tags: ['Global', 'Prestijli']
  }
];

export const CRYPTO_EXCHANGES: CryptoExchange[] = [
  {
    id: 'c_1',
    name: 'Binance TR',
    logoColor: 'bg-yellow-400',
    icon: Bitcoin,
    logoUrl: 'https://logo.clearbit.com/trbinance.com',
    commissionRate: { maker: '%0.10', taker: '%0.10' },
    coinCount: 200,
    mobileAppScore: 4.6,
    features: ['Global Likidite', 'TL Çekim/Yatırma', 'Kullanıcı Dostu', '7/24 Destek', 'Güvenlik Fonu'],
    description: 'Dünyanın en büyük borsası Binance\'in Türkiye ayağı. Global likiditeye erişim ve ücretsiz havale/EFT avantajı sunar.',
    accountOpenUrl: 'https://www.trbinance.com/account/signup',
    tags: ['Global', 'Lider']
  },
  {
    id: 'c_2',
    name: 'BtcTurk | Pro',
    logoColor: 'bg-indigo-900',
    icon: Wallet,
    logoUrl: 'https://logo.clearbit.com/btcturk.com',
    commissionRate: { maker: '%0.05', taker: '%0.09' },
    coinCount: 150,
    mobileAppScore: 4.4,
    features: ['Yerli ve Köklü', 'Düşük Komisyon', 'Profesyonel Arayüz', 'Hızlı Destek', 'Soğuk Cüzdan'],
    description: 'Türkiye\'nin ilk Bitcoin borsası. Profesyonel traderlar için düşük komisyon ve gelişmiş grafikler sunar.',
    accountOpenUrl: 'https://pro.btcturk.com/uye-ol',
    tags: ['Yerli', 'Düşük Komisyon']
  },
  {
    id: 'c_3',
    name: 'Paribu',
    logoColor: 'bg-lime-400',
    icon: Gem,
    logoUrl: 'https://logo.clearbit.com/paribu.com',
    commissionRate: { maker: '%0.25', taker: '%0.35' },
    coinCount: 180,
    mobileAppScore: 3.9,
    features: ['Kolay Arayüz', 'Geniş Altcoin', 'Paribu Box', 'Hızlı İşlem', 'Kendi Blockchain Ağı'],
    description: 'En yüksek kullanıcı sayısına sahip yerli borsalardan biri. Basit arayüzü ile yeni başlayanlar için uygundur.',
    accountOpenUrl: 'https://www.paribu.com/',
    tags: ['Popüler', 'Kolay']
  },
  {
    id: 'c_4',
    name: 'Bitexen',
    logoColor: 'bg-cyan-500',
    icon: Coins,
    logoUrl: 'https://logo.clearbit.com/bitexen.com',
    commissionRate: { maker: '%0.15', taker: '%0.25' },
    coinCount: 300,
    mobileAppScore: 4.1,
    features: ['En Geniş Coin', 'EXEN Coin Avantajı', 'Hızlı Onay', 'Yarışmalar', 'Sosyal Tokenlar'],
    description: 'Türkiye\'de en fazla kripto para çeşitliliğine sahip borsalardan biri. EXEN Coin sahiplerine düşük komisyon sunar.',
    accountOpenUrl: 'https://www.bitexen.com/sign-up',
    tags: ['Çok Çeşit', 'Kampanyalı']
  },
  {
    id: 'c_5',
    name: 'ICRYPEX',
    logoColor: 'bg-slate-900',
    icon: Gem,
    logoUrl: 'https://logo.clearbit.com/icrypex.com',
    commissionRate: { maker: '%0.15', taker: '%0.20' },
    coinCount: 100,
    mobileAppScore: 4.0,
    features: ['NFT Platformu', '7/24 Müşteri Temsilcisi', 'Kendi Kripto Fonu', 'Güvenli Altyapı', 'Analiz Desteği'],
    description: 'Kurumsal hizmet anlayışı ve NFT projeleri ile öne çıkar. Kendi kripto fonunu yöneten nadir kurumlardandır.',
    accountOpenUrl: 'https://www.icrypex.com/tr/yeni-uyelik',
    tags: ['Kurumsal', 'NFT']
  }
];

export const ICONS = {
  TrendingUp,
  ShieldCheck,
  Zap,
  Smartphone,
  Globe,
  Award,
  Bitcoin,
  Coins
};
